# Generated by Django 4.2.7 on 2023-11-29 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("excel_file", models.FileField(upload_to="uploads/mess_menu/")),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023,
                            11,
                            29,
                            17,
                            7,
                            43,
                            317581,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
            ],
        ),
    ]
