# Generated by Django 4.2.7 on 2023-11-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0002_studentprofile_bits_id_studentprofile_email_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="bits_id",
            field=models.CharField(blank=True, default=None, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="email_id",
            field=models.EmailField(
                blank=True, default=None, max_length=254, null=True
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="hostel",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="mess",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="name",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="user",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
