# Generated by Django 4.2.7 on 2023-11-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0004_remove_studentprofile_email_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="email_id",
            field=models.EmailField(
                blank=True, default=None, max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="name",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="profile_image",
            field=models.ImageField(default="default.jpg", upload_to="profile_pics"),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="user",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
