# Generated by Django 4.2.7 on 2023-11-27 19:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0006_alter_studentprofile_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentprofile",
            old_name="google_account",
            new_name="social_account",
        ),
    ]
