# Generated by Django 4.2.7 on 2023-11-27 20:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0007_rename_google_account_studentprofile_social_account"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentprofile",
            old_name="social_account",
            new_name="google_account",
        ),
    ]
