# Generated by Django 4.2.7 on 2023-11-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0008_rename_social_account_studentprofile_google_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="mess",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
