# Generated by Django 4.2.7 on 2023-11-29 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0010_complaint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="mess",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="user",
        ),
        migrations.AddField(
            model_name="complaint",
            name="author_id",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="complaint_pics"),
        ),
        migrations.AddField(
            model_name="complaint",
            name="student",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="student.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="title",
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="author",
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
