# Generated by Django 4.2.7 on 2023-11-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0011_remove_complaint_mess_remove_complaint_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("excel_file", models.FileField(upload_to="")),
                ("uploaded_at", models.DateTimeField()),
            ],
        ),
    ]
