# Generated by Django 4.2.7 on 2023-11-29 17:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0013_rename_messmenu_messmenustudent"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MessMenuStudent",
        ),
    ]
