# Generated by Django 4.2.7 on 2023-11-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0015_messmenustudent"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_to_be_served",
                    models.CharField(default=None, max_length=10, null=True),
                ),
                ("meal", models.CharField(default=None, max_length=9, null=True)),
                (
                    "item_name",
                    models.CharField(default=None, max_length=2556, null=True),
                ),
                ("rating", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.DeleteModel(
            name="MessMenuStudent",
        ),
    ]
