# Generated by Django 4.2.7 on 2023-11-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0016_menuitems_delete_messmenustudent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitems",
            name="item_name",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
