# Generated by Django 4.2.7 on 2023-12-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0020_studentbill"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentbill",
            name="breakfast",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="studentbill",
            name="dinner",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="studentbill",
            name="lunch",
            field=models.IntegerField(default=0),
        ),
    ]
