# Generated by Django 4.2.7 on 2023-12-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0021_studentbill_breakfast_studentbill_dinner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentbill",
            name="breakfast",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="studentbill",
            name="dinner",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="studentbill",
            name="lunch",
            field=models.IntegerField(),
        ),
    ]
