# Generated by Django 4.2.7 on 2023-12-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "student",
            "0022_alter_studentbill_breakfast_alter_studentbill_dinner_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="menuitems",
            old_name="rating",
            new_name="ratings",
        ),
        migrations.AddField(
            model_name="menuitems",
            name="avg_rating",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
